services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: crypto-pricing-api
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./:/app
      - type: bind
        source: .
        target: /go/src
