# syntax=docker/dockerfile:1

FROM golang:1.24-bullseye

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o ./bin/app ./cmd/main.go

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN air -v

CMD ["air", "-c", ".air.toml"]